workspace:
  base: /go
  path: src/github.com/cjsaylor/jrnl

pipeline:
  test:
    image: cjsaylor/go-alpine-sdk:1.10
    commands:
      - GO111MODULE=on go get -u golang.org/x/tools/cmd/cover
      - GO111MODULE=on go test -cover $(go list ./... | grep -v /vendor/)