builds:
  - main: ./cmd/jrnl/main.go
    binary: jrnl
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

brew:
  github:
    owner: cjsaylor
    name: homebrew-tap
  folder: Formula
  commit_author:
    name: cjsaylor
    email: cjsaylor@gmail.com
  description: "Quick and easy CLI journaling tool for Github wiki journals."
  dependencies:
    - git

release:
  prerelease: true